version: '3.8'

version: "3.8"

services:
  influxdb2:
    container_name: influxdb2
    image: influxdb:${INFLUXDB_VERSION}
    volumes:
      - ./influxdb:/root/influxdb/data
      - ./influxdb2:/var/lib/influxdb2
      - ./config.yml:/etc/influxdb2/config.yml
      # -./influxdb2-config:/etc/influxdb2
      # -./influxdb.conf:/root/influxdb/influxdb.conf
    #env_file:
      # BE SURE TO CHANGE THIS LINE BEFORE GOING TO PRODUCTION
     # - ./.env
    ports:
      - 8086:8086
    #network_mode: "bridge"
    #restart: always
    #privileged: true
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${DOCKER_INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      #- DOCKER_INFLUXDB_INIT_UPGRADE_V1_CONFIG=/root/influxdb/influxdb.conf
      


